allowBuilds:
  "@parcel/watcher": set this to true or false
  "@prisma/client": true
  "@prisma/engines": true
  "@swc/core": set this to true or false
  better-sqlite3: true
  esbuild: true
  prisma: true
minimumReleaseAgeExclude:
  - '@ai-sdk/gateway@4.0.80'
  - '@ai-sdk/mcp@2.0.49'
  - '@ai-sdk/provider-utils@5.0.40'
  - '@ai-sdk/provider@4.0.14'
  - '@ai-sdk/react@4.0.102'
  - ai@7.0.99
overrides:
  effect: ^3.20.0
  deepmerge-ts: ^8.0.0
